### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'data/stats.json'

### ISSUE THREAD

**Issue by ghost** [Tangerie/HypixelLossBot#1]

**Comment by Tangerie** [comment]
Ill commit a fix later but for now just create an empty directory called "data" in the root of the project

**Comment by ghost** [comment]
that worked but what about 


throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Missing Access

**Comment by Tangerie** [comment]
Sorry would you be able to send me the full error output?

**Comment by ghost** [comment]
Bot Loaded
[user server] Slash Commands Registered
C:\Users\user\Desktop\HypixelLossBot-master\node_modules\discord.js\src\rest\RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method,
res.status);
DiscordAPIError: Missing Access
    at RequestHandler.execute
(C:\Users\user\Desktop\HypixelLossBot-master\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push
(C:\Users\user\Desktop\HypixelLossBot-master\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
{
  method: 'post',
  path:
'/applications/871329545683341312/guilds/874016867440787466/commands',
  code: 50001,
  httpStatus: 403
}

**Comment by Tangerie** [comment]
Have you correctly registered the bot with slash command permissions?
The invite link must have the scope of applications.commands as well as bot

https://discord.com/oauth2/authorize?client_id=<client_id>&scope=bot+applications.commands
